// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twgdpjqwhdwwwuopyqkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3Z2RwanF3aGR3d3d1b3B5cWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjMwMTAsImV4cCI6MjA3MzIzOTAxMH0.70eZIonOJ5ETd1U5beHG-NP8x7zMiAgxwYRZoMuxvcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});